srun  \
    -n 1 \
    -N 1  \
    --mem=500000 \
    -p A100-80GB  \
    --gpus=4 \
    --container-mounts=/netscratch/$USER:/netscratch/$USER,/ds:/ds:ro,"`pwd`":"`pwd`" \
    --container-image=/netscratch/$USER/training.sqsh \
    --container-workdir="`pwd`" \
    --time=3-00:00 \
    --pty /bin/bash
